# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-02 10:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_auto_20161102_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminfo',
            name='item_desc',
        ),
        migrations.AddField(
            model_name='iteminfo',
            name='Item_desc',
            field=models.TextField(default=datetime.datetime(2016, 11, 2, 10, 24, 26, 802427, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
